// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkynetzMVC.Models;

namespace SkynetzMVC.Migrations
{
    [DbContext(typeof(SkynetzDbContext))]
    [Migration("20221027203334_SeedDataPlansAndTariff")]
    partial class SeedDataPlansAndTariff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SkynetzMVC.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FreeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            FreeMinutes = 60,
                            Name = "FaleMais 60"
                        },
                        new
                        {
                            Id = 3,
                            FreeMinutes = 120,
                            Name = "FaleMais 120"
                        });
                });

            modelBuilder.Entity("SkynetzMVC.Models.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MinuteValue")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Destination = "011",
                            MinuteValue = 2.8999999999999999,
                            Source = "016"
                        },
                        new
                        {
                            Id = 3,
                            Destination = "017",
                            MinuteValue = 1.7,
                            Source = "011"
                        },
                        new
                        {
                            Id = 4,
                            Destination = "011",
                            MinuteValue = 2.7000000000000002,
                            Source = "017"
                        },
                        new
                        {
                            Id = 5,
                            Destination = "018",
                            MinuteValue = 0.90000000000000002,
                            Source = "011"
                        },
                        new
                        {
                            Id = 6,
                            Destination = "011",
                            MinuteValue = 1.8999999999999999,
                            Source = "018"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
